---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: beatljs/pyubuntu:systemd
    pre_build_image: true
    command: systemd
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
