---
- name: Get and Extract Vector
  block:
  - name: Create temp directory
    ansible.builtin.file:
      path: "{{ temp_dir }}"
      state: directory
      mode: 0755
  - name: Get vector distrib
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "{{ temp_dir }}/vector-{{ vector_version }}.tar.gz"
      mode: '0755'
  - name: Create root directory
    ansible.builtin.file:
      path: "{{ temp_dir }}/vector-{{ vector_version }}"
      state: directory
      mode: 0755
  - name: Extract vector
    ansible.builtin.unarchive:
      src: "{{ temp_dir }}/vector-{{ vector_version }}.tar.gz"
      dest: "{{ temp_dir }}/vector-{{ vector_version }}/"
      extra_opts: [--strip-components=2]
      remote_src: yes
    when: not ansible_check_mode
- name: Install and Configure Vector
  become: true
  block:
  - name: Copy vector to bin with owner and permissions
    when: not ansible_check_mode
    ansible.builtin.copy:
      src: "{{ temp_dir }}/vector-{{ vector_version }}/bin/vector"
      dest: /usr/bin/vector
      mode: 0755
      remote_src: true
  - name: Configure vector.service from template
    tags:
      - vector_service
    ansible.builtin.template:
      src: vector.service.j2
      dest: /etc/systemd/system/vector.service
      mode: 0644
  - name: Create config dir for vector
    ansible.builtin.file:
      path: "{{ vector_config_dir }}"
      state: directory
      mode: 0644
  - name: Configure vector from template
    ansible.builtin.template:
      src: vector.yml.j2
      dest: "{{ vector_config_dir }}/vector.yml"
      mode: 0644
  - name: Create data directory
    ansible.builtin.file:
      path: "{{ vector_config.data_dir }}"
      state: directory
      mode: 0777
    notify: Restart Vector service
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
