---
# tasks file for vector-role
    - name: Vector | Get distrib
      tags: vector
      ansible.builtin.get_url:
        url: "{{ vector_url }}/{{ vector_version }}/{{ vector_package }}_{{ vector_version }}-1_amd64.deb"
        dest: "./{{ vector_package }}-{{ vector_version }}.deb"

    - name: Vector | Install package
      tags: vector
      become: true
      ansible.builtin.apt:
        deb: "./{{ vector_package }}-{{ vector_version }}.deb"

    - name: Vector | Configure | ensure what config directory exists
      tags: vector
      file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: 0755

    - name: Vector | Configure | Template config
      tags: vector
      ansible.builtin.template:
        src: ./templates/my_vector_cfg.j2
        mode: 0644
        dest: "{{ vector_config_dir }}/vector.yml"

    - name: Vector | Prepare and setup unit from template
      tags: vector
      become: true
      ansible.builtin.template:
        src: ./templates/my_vector_service.j2
        dest: /etc/systemd/system/vector.service
        mode: 0644
      notify: Vector | Restart Service

    - name: Vector | Flush handlers
      tags: vector
      meta: flush_handlers

    - name: Vector | Create Log Dir
      tags: vector
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ vector_log_dir }}"
        mode: u=rwx,g=rwx,o=rwx

